FROM node:22-alpine
WORKDIR /app

# Copy dependency files and install
COPY package*.json ./
RUN npm install

# Copy the rest of the frontend code
COPY . .

EXPOSE 5173

# Start Vite and expose it to the Docker network
CMD ["npm", "run", "dev", "--", "--host"]