import {
  index,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  vector,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// ==========================================
// 1. USERS (The AI Consumer Profile)
// ==========================================
export const users = pgTable('users', {
  // Uses the UUID/UID generated by Supabase/Firebase Auth
  // Changed from uuid to text to be future-proof for Firebase UID (which are strings)
  id: text('id').primaryKey(), 
  email: text('email').notNull().unique(),
  displayName: text('display_name').notNull(),
  
  // THE FLEX: A mathematical representation of what the user likes to drink.
  // The RootAgent updates this as the user interacts with the app.
  tasteEmbedding: vector('taste_embedding', { dimensions: 768 }),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// 2. INVENTORY (The Barback's Domain)
// ==========================================
export const inventory = pgTable('inventory', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  
  spiritName: text('spirit_name').notNull(), // e.g., "Hendrick's Gin"
  category: text('category').notNull(),      // e.g., "Gin"
  
  // Tracked in 8ths (0-8)
  volumeEighths: integer('volume_eighths').notNull().default(8), 
  
  // For the PricingAgent to track the value of the home bar
  purchasePrice: numeric('purchase_price', { precision: 10, scale: 2 }), 

  // Flavor profile numeric attributes (0.00 - 1.00 scale suggested)
  // Flavor profile numeric attributes (0.00 - 1.00 scale suggested)
  // Flavor profile numeric attributes (0.00 - 1.00 scale suggested)
  // These fields are optional; the migration `0001_add_flavor_profiles.sql`
  // creates the columns in the database. They are kept here so Drizzle has
  // the correct types available for inserts/queries when you migrate.
  flavor_sweetness: numeric('flavor_sweetness', { precision: 3, scale: 2 }),
  flavor_bitterness: numeric('flavor_bitterness', { precision: 3, scale: 2 }),
  flavor_sourness: numeric('flavor_sourness', { precision: 3, scale: 2 }),
  flavor_body: numeric('flavor_body', { precision: 3, scale: 2 }),

  // A vector embedding representation of the spirit's flavor/profile
  flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),

  // Number of unopened full bottles of this spirit (0-99)
  // Keeps the model simple: one open bottle tracked by `volumeEighths` plus
  // a count of unopened bottles available in reserve.
  unopenedCount: integer('unopened_count').notNull().default(0),

  // Optional FK to a canonical ingredient entry. Nullable to allow gradual migration
  // from free-text `spiritName` to structured `ingredients` table.
  ingredientId: integer('ingredient_id'),
  
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// ==========================================
// 3. RECIPES (The Global AI Knowledge Base)
// ==========================================
export const recipes = pgTable(
  'recipes',
  {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    category: text('category').notNull(),
    ingredients: text('ingredients').array().notNull(),
    instructions: text('instructions').notNull(),
    youtubeUrl: text('youtube_url'), // For the MixologistAgent to serve videos
    
    // The vector representation of the drink's flavor
    embedding: vector('embedding', { dimensions: 768 }),

    // Optional numeric flavor profile attributes (0.00 - 1.00 scale suggested)
    // These fields are optional and match the migration added to the DB. They
    // allow the Mixologist and Inventory agents to store per-item flavor
    // attributes and a dedicated flavor vector for nearest-neighbor searches.
    flavor_sweetness: numeric('flavor_sweetness', { precision: 3, scale: 2 }),
    flavor_bitterness: numeric('flavor_bitterness', { precision: 3, scale: 2 }),
    flavor_sourness: numeric('flavor_sourness', { precision: 3, scale: 2 }),
    flavor_body: numeric('flavor_body', { precision: 3, scale: 2 }),

    // Flavor embedding separate from any generic embedding field
    flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),
  },
  (table) => [
    index('recipeEmbeddingIndex').using('hnsw', table.embedding.op('vector_cosine_ops')),
  ]
);

// ==========================================
// INGREDIENTS (Canonical ingredient records)
// ==========================================
export const ingredients = pgTable('ingredients', {
  id: serial('id').primaryKey(),
  name: text('name').notNull().unique(),
  type: text('type').notNull(), // e.g., 'spirit', 'mixer', 'garnish', 'sweetener'
  unit: text('unit'),
  defaultVolumeMl: numeric('default_volume_ml', { precision: 8, scale: 2 }),
  perishable: integer('perishable').default(0),
  category: text('category'),
  flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// RECIPE_INGREDIENTS (Join table)
// ==========================================
export const recipeIngredients = pgTable('recipe_ingredients', {
  id: serial('id').primaryKey(),
  recipeId: integer('recipe_id').references(() => recipes.id, { onDelete: 'cascade' }).notNull(),
  ingredientId: integer('ingredient_id').references(() => ingredients.id, { onDelete: 'restrict' }).notNull(),
  amountText: text('amount_text'),
  amountMl: numeric('amount_ml', { precision: 8, scale: 2 }),
  position: integer('position').default(0),
});

// ==========================================
// 4. USER FAVORITES (The Training Data)
// ==========================================
// A junction table. Every time a user favorites a drink, a background task 
// recalculates their users.tasteEmbedding vector based on the recipes they like.
export const userFavorites = pgTable('user_favorites', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  recipeId: integer('recipe_id')
    .references(() => recipes.id, { onDelete: 'cascade' })
    .notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// 5. SHOPPING LIST (What the User Needs)
// ==========================================
export const shoppingList = pgTable('shopping_list', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  
  itemName: text('item_name').notNull(), // e.g., "Tequila"
  quantity: integer('quantity').default(1).notNull(),
  isPurchased: integer('is_purchased').default(0).notNull(), // 0 = false, 1 = true (using integer for simplicity)

  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// RELATIONS (For clean type-safe queries)
// ==========================================
export const usersRelations = relations(users, ({ many }) => ({
  inventory: many(inventory),
  favorites: many(userFavorites),
  shoppingList: many(shoppingList),
}));

export const ingredientsRelations = relations(ingredients, ({ many }) => ({
  recipeReferences: many(recipeIngredients),
}));

export const recipesRelations = relations(recipes, ({ many }) => ({
  ingredients: many(recipeIngredients),
}));

export const inventoryRelations = relations(inventory, ({ one }) => ({
  ingredient: one(ingredients, { fields: [inventory.ingredientId], references: [ingredients.id] }),
}));
