import {
  index,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  uuid,
  vector,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// ==========================================
// 1. USERS (The AI Consumer Profile)
// ==========================================
export const users = pgTable('users', {
  // Uses the UUID generated by Supabase/Firebase Auth
  id: uuid('id').primaryKey(), 
  email: text('email').notNull().unique(),
  displayName: text('display_name').notNull(),
  
  // THE FLEX: A mathematical representation of what the user likes to drink.
  // The RootAgent updates this as the user interacts with the app.
  tasteEmbedding: vector('taste_embedding', { dimensions: 768 }),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// 2. INVENTORY (The Barback's Domain)
// ==========================================
export const inventory = pgTable('inventory', {
  id: serial('id').primaryKey(),
  userId: uuid('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  
  spiritName: text('spirit_name').notNull(), // e.g., "Hendrick's Gin"
  category: text('category').notNull(),      // e.g., "Gin"
  
  // Tracked in 8ths (0-8)
  volumeEighths: integer('volume_eighths').notNull().default(8), 
  
  // For the PricingAgent to track the value of the home bar
  purchasePrice: numeric('purchase_price', { precision: 10, scale: 2 }), 
  
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// ==========================================
// 3. RECIPES (The Global AI Knowledge Base)
// ==========================================
export const recipes = pgTable(
  'recipes',
  {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    category: text('category').notNull(),
    ingredients: text('ingredients').array().notNull(),
    instructions: text('instructions').notNull(),
    youtubeUrl: text('youtube_url'), // For the MixologistAgent to serve videos
    
    // The vector representation of the drink's flavor
    embedding: vector('embedding', { dimensions: 768 }),
  },
  (table) => [
    index('recipeEmbeddingIndex').using('hnsw', table.embedding.op('vector_cosine_ops')),
  ]
);

// ==========================================
// 4. USER FAVORITES (The Training Data)
// ==========================================
// A junction table. Every time a user favorites a drink, a background task 
// recalculates their users.tasteEmbedding vector based on the recipes they like.
export const userFavorites = pgTable('user_favorites', {
  id: serial('id').primaryKey(),
  userId: uuid('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  recipeId: integer('recipe_id')
    .references(() => recipes.id, { onDelete: 'cascade' })
    .notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// RELATIONS (For clean type-safe queries)
// ==========================================
export const usersRelations = relations(users, ({ many }) => ({
  inventory: many(inventory),
  favorites: many(userFavorites),
}));
