import {
  index,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  vector,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// ==========================================
// 1. USERS (The AI Consumer Profile)
// ==========================================
export const users = pgTable('users', {
  // Uses the UUID/UID generated by Supabase/Firebase Auth
  // Changed from uuid to text to be future-proof for Firebase UID (which are strings)
  id: text('id').primaryKey(), 
  email: text('email').notNull().unique(),
  displayName: text('display_name').notNull(),
  
  // THE FLEX: A mathematical representation of what the user likes to drink.
  // The RootAgent updates this as the user interacts with the app.
  tasteEmbedding: vector('taste_embedding', { dimensions: 768 }),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// 2. INVENTORY (The Barback's Domain)
// ==========================================
export const inventory = pgTable('inventory', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  
  spiritName: text('spirit_name').notNull(), // e.g., "Hendrick's Gin"
  category: text('category').notNull(),      // e.g., "Gin"
  
  // Tracked in 8ths (0-8)
  volumeEighths: integer('volume_eighths').notNull().default(8), 
  
  // For the PricingAgent to track the value of the home bar
  purchasePrice: numeric('purchase_price', { precision: 10, scale: 2 }), 

  // Flavor profile numeric attributes (0.00 - 1.00 scale suggested)
  // Flavor profile numeric attributes (0.00 - 1.00 scale suggested)
  // Flavor profile numeric attributes (0.00 - 1.00 scale suggested)
  // These fields are optional; the migration `0001_add_flavor_profiles.sql`
  // creates the columns in the database. They are kept here so Drizzle has
  // the correct types available for inserts/queries when you migrate.
  flavor_sweetness: numeric('flavor_sweetness', { precision: 3, scale: 2 }),
  flavor_bitterness: numeric('flavor_bitterness', { precision: 3, scale: 2 }),
  flavor_sourness: numeric('flavor_sourness', { precision: 3, scale: 2 }),
  flavor_body: numeric('flavor_body', { precision: 3, scale: 2 }),

  // A vector embedding representation of the spirit's flavor/profile
  flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),

  // Number of unopened full bottles of this spirit (0-99)
  // Keeps the model simple: one open bottle tracked by `volumeEighths` plus
  // a count of unopened bottles available in reserve.
  unopenedCount: integer('unopened_count').notNull().default(0),

  // Optional FK to a canonical ingredient entry. Nullable to allow gradual migration
  // from free-text `spiritName` to structured `ingredients` table.
  ingredientId: integer('ingredient_id'),
  // Optional image URL for the bottle label or photo (public URL)
  imageUrl: text('image_url'),

  // Whether the user has marked this bottle as a favourite
  isFavorite: integer('is_favorite').notNull().default(0),

  // User's personal 1-5 star rating for this bottle (null = unrated)
  rating: integer('rating'),

  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// ==========================================
// 3. RECIPES (The Global AI Knowledge Base)
// ==========================================
export const recipes = pgTable(
  'recipes',
  {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    category: text('category').notNull(),
    ingredients: text('ingredients').array().notNull(),
    instructions: text('instructions').notNull(),
    youtubeUrl: text('youtube_url'), // For the MixologistAgent to serve videos
    
    // The vector representation of the drink's flavor
    embedding: vector('embedding', { dimensions: 768 }),

    // Optional numeric flavor profile attributes (0.00 - 1.00 scale suggested)
    // These fields are optional and match the migration added to the DB. They
    // allow the Mixologist and Inventory agents to store per-item flavor
    // attributes and a dedicated flavor vector for nearest-neighbor searches.
    flavor_sweetness: numeric('flavor_sweetness', { precision: 3, scale: 2 }),
    flavor_bitterness: numeric('flavor_bitterness', { precision: 3, scale: 2 }),
    flavor_sourness: numeric('flavor_sourness', { precision: 3, scale: 2 }),
    flavor_body: numeric('flavor_body', { precision: 3, scale: 2 }),

    // Flavor embedding separate from any generic embedding field
    flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),
    // Optional public image URL for the recipe (e.g., finished cocktail photo)
    imageUrl: text('image_url'),

    // Rich display fields for the frontend recipe cards
    baseSpirit:  text('base_spirit'),
    abv:         text('abv'),
    glassType:   text('glass_type'),
    difficulty:  text('difficulty'),
    imageEmoji:  text('image_emoji'),

    // User's personal 1-5 star rating for this cocktail (null = unrated)
    rating: integer('rating'),

    // Bar tools/equipment needed (e.g. ["🫗 Cocktail Shaker", "🪤 Hawthorne Strainer"])
    equipment: text('equipment').array(),
  },
  (table) => [
    index('recipeEmbeddingIndex').using('hnsw', table.embedding.op('vector_cosine_ops')),
  ]
);

// ==========================================
// INGREDIENTS (Canonical ingredient records)
// ==========================================
export const ingredients = pgTable('ingredients', {
  id: serial('id').primaryKey(),
  name: text('name').notNull().unique(),
  type: text('type').notNull(), // e.g., 'spirit', 'mixer', 'garnish', 'sweetener'
  unit: text('unit'),
  defaultVolumeMl: numeric('default_volume_ml', { precision: 8, scale: 2 }),
  perishable: integer('perishable').default(0),
  category: text('category'),
  flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// RECIPE_INGREDIENTS (Join table)
// ==========================================
export const recipeIngredients = pgTable('recipe_ingredients', {
  id: serial('id').primaryKey(),
  recipeId: integer('recipe_id').references(() => recipes.id, { onDelete: 'cascade' }).notNull(),
  ingredientId: integer('ingredient_id').references(() => ingredients.id, { onDelete: 'restrict' }).notNull(),
  amountText: text('amount_text'),
  amountMl: numeric('amount_ml', { precision: 8, scale: 2 }),
  position: integer('position').default(0),
});

// ==========================================
// RECIPE STEPS (Cached ordered instructions)
// ==========================================
// Written once by the MixologistAgent on a cache miss; read many times after.
// Belongs to a base recipe (variantId = null) or a specific variant.
export const recipeSteps = pgTable('recipe_steps', {
  id: serial('id').primaryKey(),
  recipeId: integer('recipe_id')
    .references(() => recipes.id, { onDelete: 'cascade' })
    .notNull(),
  // Null = step belongs to the base recipe; set = step belongs to a variant
  variantId: integer('variant_id'),
  position: integer('position').notNull().default(0),
  stepText: text('step_text').notNull(),
  // Optional helper metadata so the UI can show timing / equipment tips
  durationSeconds: integer('duration_seconds'),
  toolRequired: text('tool_required'), // e.g. "cocktail shaker", "muddler"
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// RECIPE VARIANTS (Upgrade paths)
// ==========================================
// Lets the agent cache "same drink, better ingredients" without duplicating the
// base recipe.  Example: standard Margarita (base) → Grand Marnier Upgrade
// (variant).  Each variant can override the ingredient list, instructions, and
// flavor profile so the frontend can show "you could make it this way instead".
export const recipeVariants = pgTable('recipe_variants', {
  id: serial('id').primaryKey(),
  baseRecipeId: integer('base_recipe_id')
    .references(() => recipes.id, { onDelete: 'cascade' })
    .notNull(),

  // Human-readable upgrade label shown in the UI
  variantLabel: text('variant_label').notNull(), // e.g. "Grand Marnier Upgrade"
  // Short description of what changed and why it matters
  variantNote: text('variant_note'),            // e.g. "Richer orange flavour, smoother finish"

  // Overriding ingredient list (mirrors recipes.ingredients — free-text array)
  ingredients: text('ingredients').array().notNull(),
  // Override instructions for this variant (null = reuse base recipe instructions)
  instructions: text('instructions'),
  // Optional image for the upgraded version
  imageUrl: text('image_url'),

  // Flavor profile for this specific variant so the agent can do NN searches
  // without regenerating the embedding on every request.
  flavor_sweetness: numeric('flavor_sweetness', { precision: 3, scale: 2 }),
  flavor_bitterness: numeric('flavor_bitterness', { precision: 3, scale: 2 }),
  flavor_sourness: numeric('flavor_sourness', { precision: 3, scale: 2 }),
  flavor_body: numeric('flavor_body', { precision: 3, scale: 2 }),
  flavorEmbedding: vector('flavor_embedding', { dimensions: 768 }),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// ==========================================
// 4. USER FAVORITES (The Training Data)
// ==========================================
// A junction table. Every time a user favorites a drink, a background task 
// recalculates their users.tasteEmbedding vector based on the recipes they like.
export const userFavorites = pgTable('user_favorites', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  recipeId: integer('recipe_id')
    .references(() => recipes.id, { onDelete: 'cascade' })
    .notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// 5. SHOPPING LIST (What the User Needs)
// ==========================================
export const shoppingList = pgTable('shopping_list', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .references(() => users.id, { onDelete: 'cascade' })
    .notNull(),
  
  itemName: text('item_name').notNull(), // e.g., "Tequila"
  quantity: integer('quantity').default(1).notNull(),
  isPurchased: integer('is_purchased').default(0).notNull(), // 0 = false, 1 = true (using integer for simplicity)

  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// ==========================================
// RELATIONS (For clean type-safe queries)
// ==========================================
export const usersRelations = relations(users, ({ many }) => ({
  inventory: many(inventory),
  favorites: many(userFavorites),
  shoppingList: many(shoppingList),
}));

export const ingredientsRelations = relations(ingredients, ({ many }) => ({
  recipeReferences: many(recipeIngredients),
}));

export const recipesRelations = relations(recipes, ({ many }) => ({
  ingredients: many(recipeIngredients),
  steps: many(recipeSteps),
  variants: many(recipeVariants),
}));

export const recipeVariantsRelations = relations(recipeVariants, ({ one, many }) => ({
  baseRecipe: one(recipes, { fields: [recipeVariants.baseRecipeId], references: [recipes.id] }),
  steps: many(recipeSteps),
}));

export const recipeStepsRelations = relations(recipeSteps, ({ one }) => ({
  recipe: one(recipes, { fields: [recipeSteps.recipeId], references: [recipes.id] }),
  variant: one(recipeVariants, { fields: [recipeSteps.variantId], references: [recipeVariants.id] }),
}));

export const inventoryRelations = relations(inventory, ({ one }) => ({
  ingredient: one(ingredients, { fields: [inventory.ingredientId], references: [ingredients.id] }),
}));
